[build]
command = "cd frontend && npm run build"
publish = "frontend/build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
REACT_APP_API_URL = "https://email-spam-detection-production-2f54.up.railway.app"

[context.production.environment]
REACT_APP_API_URL = "https://email-spam-detection-production-2f54.up.railway.app"
